# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
        environment:
          - POSTGRES_USER=root
          - POSTGRES_DB=circle_test
          - POSTGRES_PASSWORD=root
      - image: circleci/postgres:10
        environment:
          - POSTGRES_USER=root
          - POSTGRES_DB=circle_test
          - POSTGRES_PASSWORD=root
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - npm test